plugins:
  - prettier
extends:
  - eslint-config-redlotus-next/dist/main
  - plugin:prettier/recommended
rules: 
  prettier/prettier:
    - error
    - semi: true
    - tabWidth: 2
    - singleQuote: false
    - trailingComma: es5
    - arrowParens: avoid
    - printWidth: 100
    - endOfLine: auto
    - usePrettierrc: false