name: CI

on: [push, pull_request]

env:
  ANALYZE: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Typecheck
        run: yarn typecheck

      - name: Lint fix
        run: yarn lint:fix

      - name: Lint
        run: yarn lint

      - name: Print Environment Variable
        run: echo $ANALYZE